trigger:
  branches:
    include:
      - 2.x
  paths:
    include:
      - config/*
      - Connectors/src/AspDotNetCore/MySqlEF6/*

variables:
  - group: 'Samples Configuration and Credentials'

jobs:
  -
    template: ../../../../ci/templates/cloud-foundry-job.yml
    parameters:
      feature: Connectors
      sample: MySqlEF6
