version: '3.2'
services:
  config:
    image: "steeltoeoss/config-server"
    command: --spring.profiles.active=native --spring.cloud.config.server.native.searchLocations=/config
    volumes:
      - type: bind
        source: ./src/config
        target: /config
    ports:
      - "8888:8888"
  eureka:
    image: "steeltoeoss/eurekaserver"
    ports:
      - "8761:8761"
  mysql:
    image: "mysql:5.7"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: steeltoe
      MYSQL_DATABASE: steeltoe
      MYSQL_USER: steeltoe
      MYSQL_PASSWORD: steeltoe
