eureka:
  client:
    shouldRegisterWithEureka: true
mysql:
  client:
    database: MusicStore
sqlserver:
  credentials:
    database: MusicStore
redis:
  client:
    host: redis
DefaultAdminUsername: Administrator@test.com
DefaultAdminPassword: YouShouldChangeThisPassword1!
