parameters:
  feature: ''
  sample: ''
  behave_args: '--stop --tags ~@wip'
jobs:
- job: ${{parameters.feature}}_${{parameters.sample}}
  timeoutInMinutes: 90
  displayName: '${{parameters.feature}}: ${{parameters.sample}}'
  pool:
    vmImage: ubuntu-latest
  steps:
  - template: setup-cloud-foundry-linux-steps.yaml
  - bash: ./behave.sh ${{parameters.feature}}/src/${{parameters.sample}} ${{parameters.behave_args}} --tags ~@net461
    displayName: 'Sample -> ${{parameters.feature}}: ${{parameters.sample}}'
  - template: publish-results-steps.yaml
    parameters:
      feature: ${{parameters.feature}}
      sample: ${{parameters.sample}}
      os: Linux
