trigger:
  branches:
    include:
      - 2.x
  paths:
    include:
      - config/*
      - Connectors/src/AspDotNetCore/MySql/*

variables:
  - group: 'Samples Configuration and Credentials'

jobs:
  -
    template: templates/cloud-foundry-job.yaml
    parameters:
      feature: Connectors
      sample: MySql
