trigger:
  branches:
    include:
      - master
  paths:
    include:
      - config/*
      - Connectors/src/AspDotNetCore/PostgreEFCore/*

variables:
  - group: 'Samples Configuration and Credentials'

jobs:
  -
    template: templates/cloud-foundry-job.yaml
    parameters:
      feature: Connectors
      sample: PostgreEFCore
