trigger:
  branches:
    include:
      - 2.x
  paths:
    include:
      - config/*
      - Configuration/src/AspDotNetCore/CloudFoundry/*

# skip pipeline for PRs
pr: none

variables:
  - group: 'Samples Configuration and Credentials'

jobs:
  - template: templates/cloud-foundry-job.yaml
    parameters:
      feature: Configuration
      sample: CloudFoundry
