trigger:
  branches:
    include:
      - master
  paths:
    include:
      - config/*
      - Configuration/src/SimpleCloudFoundry/*

variables:
  - group: 'Samples Configuration and Credentials'

jobs:
  -
    template: templates/cloud-foundry-job.yaml
    parameters:
      feature: Configuration
      sample: SimpleCloudFoundry
