trigger:
  branches:
    include:
      - master
  paths:
    include:
      - config/*
      - Management/src/AspDotNetCore/CloudFoundry/*

variables:
  - group: 'Samples Configuration and Credentials'

jobs:
  -
    template: ../../../../ci/templates/cloud-foundry-job.yml
    parameters:
      feature: Management
      sample: CloudFoundry
